B0: 3
RFon: false
dchi0: 0.18
gamma: 267.5
nechoes: 2
pixdim:
- 2.75
- 2.75
- 5.0
tauvec:
- 19.0
- 20.0
- 6.5
- 8.5
- 1.0
- 16.5
- 1.5
- 14.5
- 3.5
- 13.0
- 9.0
- 19.5
- 17.0
- 2.5
- 4.5
- 12.5
- 2.0
- 9.5
- 6.0
- 14.0
- 7.5
- 5.5
- 12.0
- 8.0
- 11.0
- 0.5
- 16.0
- 10.5
- 13.5
- 5.0
- 10.0
- 0.0
- 18.5
- 17.5
- 3.0
- 11.5
- 7.0
- 18.0
- 15.5
- 15.0
- 4.0
te1: 64.0
te2: 107.0
tr: 4400.0
